# For detailed information about docker-compose visit https://docs.docker.com/compose/
# To start all docker containers required to execute the tests locally run:
# docker-compose up

version: '2'
services:
  amqp:
    image: rabbitmq:3
    ports:
      - "5672:5672"
  cassandra:
    image: cassandra:3.0.15
    ports:
      - "9042:9042"
  orientdb:
    image: orientdb:latest
    ports:
      - "2424:2424"
    environment:
      - "ORIENTDB_ROOT_PASSWORD=root"
    command: /orientdb/bin/server.sh -Dmemory.chunk.size=268435456
  dynamodb:
    image: deangiberson/aws-dynamodb-local
    ports:
      - "8001:8000"
  geode:
    container_name: geode
    image: apachegeode/geode:1.4.0
    hostname: geode
    mem_limit: 2g
    expose:
      - "10334"
      - "1099"
      - "7575"
      - "40404"
    ports:
      - "1099:1099"
      - "10334:10334"
      - "7575:7575"
      - "7070:7070"
      - "40404:40404"
      - "8081:8080"
    volumes:
      - ./geode/scripts/:/scripts/
    command: /scripts/geode.sh
  ironauth:
    image: iron/auth
    ports:
      - "8090:8090"
  ironmq:
    image: iron/mq
    links:
      - "ironauth:ironauth"
    environment:
      - "AUTH_HOST=http://ironauth:8090"
    ports:
      - "8080:8080"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  mqtt:
    image: toke/mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/src/test/travis:/mqtt/config/conf.d